import asyncio
import os
import sys

# Define the exact curriculum structure from frontend QuizSelection.jsx
CURRICULUM = {
    "unit1": [
        "Evolution of management thoughts from ancient/medieval to modern times in India (IKS)",
        "Management: meaning, importance, characteristics, functions & challenges",
        "Introduction to scientific management - Taylor's & Fayol's principles of management",
        "Levels & functions of management at supervisory level",
        "Self-management skills",
        "Overview of Managerial Skills"
    ],
    "unit2": [
        "Creativity and innovation management",
        "New product development, change management",
        "Product Management",
        "Agile product management",
        "Project Management",
        "Tools of Project Management"
    ],
    "unit3": [
        "Quality circle, kaizen, Six Sigma, TQM",
        "5S, Kanban card system, TPM, Lean Manufacturing",
        "Quality Standards and ISO",
        "The overview of ERP",
        "Service quality and customer/client satisfaction"
    ],
    "unit4": [
        "Marketing management",
        "Needs, wants, and demands in marketing. CRM",
        "Types of marketing: Traditional and digital marketing",
        "Event management"
    ],
    "unit5": [
        "Overview of Supply Chain and logistics Management",
        "Components of Supply Chain and logistics Management",
        "Role of information technology in supply chain & logistics management",
        "Overview of Human Resource Management",
        "Recruitment, selection, and training of human resources",
        "Qualities of a successful supervisor/team leader"
    ]
}

async def seed_quizzes():
    # Explicitly load the backend .env file
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    env_path = os.path.join(project_root, "backend", ".env")
    from dotenv import load_dotenv
    load_dotenv(env_path)
    
    # Verify DATABASE_URL
    db_url = os.getenv("DATABASE_URL")
    print(f"📊 Using Database URL: {db_url}")

    # Lazy imports to ensure environment is set up
    from backend.app.database import AsyncSessionLocal, engine, Base
    from backend.app.models.models import MCQ
    from backend.app.utils.ai_generator import generate_mcqs
    
    # Ensure tables exist and clear old MCQ data to prevent duplicates / mismatches
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        from sqlalchemy import delete
        await conn.execute(delete(MCQ))
    
    async with AsyncSessionLocal() as session:
        print("🚀 Starting ManageMind Quiz Seeding...")
        total_added = 0
        
        for unit, topics in CURRICULUM.items():
            print(f"\n📂 Processing Unit {unit}...")
            for topic in topics:
                # Add delay to avoid 429 rate limits
                if total_added > 0:
                    print(f"  ⏳ Waiting 10s for API quota...")
                    await asyncio.sleep(10)
                
                print(f"  📝 Generating MCQs for: {topic}...")
                try:
                    # Requesting 10 questions per topic to ensure a comprehensive pool
                    questions = await generate_mcqs(f"MSBTE Management (22509) - Unit {unit}: {topic}", count=10)
                    
                    if not questions or len(questions) < 10:
                        print(f"  ⚠️ Only {len(questions)} questions generated by AI. Adding standard fallback questions for {topic}.")
                        # Supplement with generic but relevant questions if AI under-delivers
                        fallbacks = [
                            {
                                "question": f"Which of the following is a key aspect of {topic}?",
                                "options": [
                                    {"id": "a", "text": "Continuous Process Improvement"},
                                    {"id": "b", "text": "Stagnation of Workflows"},
                                    {"id": "c", "text": "Decreasing Organizational Efficiency"},
                                    {"id": "d", "text": "Ignoring Stakeholder Requirements"}
                                ],
                                "correct_option_id": "a",
                                "explanation": f"In {topic}, the focus is always on improving processes and achieving better organizational outcomes."
                            },
                            {
                                "question": f"What role does planning play in {topic}?",
                                "options": [
                                    {"id": "a", "text": "It is irrelevant to the outcome"},
                                    {"id": "b", "text": "It serves as the foundation for execution"},
                                    {"id": "c", "text": "It only consumes resources without benefit"},
                                    {"id": "d", "text": "It is done after the work is complete"}
                                ],
                                "correct_option_id": "b",
                                "explanation": f"Effective {topic} requires thorough planning to set clear objectives and resource allocation."
                            }
                        ]
                        # Add only enough to hit a reasonable variety
                        for f_q in fallbacks:
                            if len(questions) < 10:
                                questions.append(f_q)
                        
                    for q_data in questions:
                        mcq = MCQ(
                            unit=unit,
                            topic=topic,
                            question=q_data["question"],
                            options=q_data["options"],
                            correct_option_id=q_data["correct_option_id"],
                            explanation=q_data["explanation"]
                        )
                        session.add(mcq)
                    
                    total_added += len(questions)
                    print(f"  ✅ Added {len(questions)} questions.")
                    # Commit per topic to ensure progress is saved if a crash occurs
                    await session.commit()
                except Exception as e:
                    print(f"  ❌ Error processing {topic}: {e}")
                    await session.rollback()
        
        print(f"\n✨ Seeding completed! Total questions added: {total_added}")

if __name__ == "__main__":
    # Ensure project root is in path
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    if project_root not in sys.path:
        sys.path.insert(0, project_root)
        
    asyncio.run(seed_quizzes())
